Adicionando o componente 'ClassComponent' no projeto
erikvix/React-playground pull request #1
Opened 2024-06-26 23:22 UTC by erikvix

# Descrição
Este Pull requeste apresenta um novo componente de classe React ClassComponent que busca e exibe uma piada aleatória da [Official Joke API](https://official-joke-api.appspot.com/).

# Checklist 
- [x] Código está compilando sem erros
- [x] Não tem erros de linter

# Screenshots/Vídeo
![image](https://github.com/erikvix/React-playground/assets/124940063/269eba4c-d13a-4288-b75a-dc43013330da)
![image](https://github.com/erikvix/React-playground/assets/124940063/b1714640-2906-4cba-aef8-3f75adddf6c5)

2024-06-26 23:50 UTC, mikaelhadler requested changes

2024-06-26 23:50 UTC, mikaelhadler commented on src/components/ClassComponent/index.jsx
> +    this.handleFetch = this.handleFetch.bind(this);
Por você incluiu o este handle dentro do construtor?

2024-06-26 23:50 UTC, mikaelhadler commented on src/components/ClassComponent/index.jsx
> +      apiUrl: "https://official-joke-api.appspot.com/random_joke",
Você não precisa da url dentro do state, criei uma const fora do componente e use ela

2024-06-26 23:50 UTC, mikaelhadler commented on src/components/ClassComponent/index.jsx
> +    axios
Você não precisa do axios, remova o axios e use o fetch nativo

2024-06-26 23:50 UTC, mikaelhadler commented on src/components/ClassComponent/index.jsx
> +        method: "GET",
Você já definiu que o método usado é get quando usou o axios.get, isso é redundante

2024-06-26 23:50 UTC, mikaelhadler commented on src/components/ClassComponent/index.jsx
> +        this.setState({ loading: false });
O set loading deveria estar no .finally e não duplicado

2024-06-26 23:50 UTC, mikaelhadler commented on src/components/ClassComponent/index.jsx
> +        <h1 style={{ color: "#FF7D00" }}>Every Day Joke</h1>
Crie um arquivo css, style inline é uma má prática e somente deve ser usando quando estritamente necessário

2024-06-27 00:48 UTC, erikvix commented on src/components/ClassComponent/index.jsx
> +    this.handleFetch = this.handleFetch.bind(this);
Eu não sei mas a função só funcionou com ele dentro do construtor, vou pesquisar sobre e daria uma resposta mais concreta

2024-06-27 00:51 UTC, mikaelhadler requested changes

2024-06-27 00:51 UTC, mikaelhadler commented on src/components/ClassComponent/index.jsx
> +    })
No get n precisa definir de forma explícita, ele já assume por default se não tiver nada definido que é get
```suggestion
    fetch(apiUrl)
```

2024-07-02 19:47 UTC, merged